export const UPLOAD_FETCHING = 'UPLOAD_FETCHING';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAILED = 'UPLOAD_FAILED';
export const SHOW_TOAST = 'SHOW_TOAST';

export const RETURN_RIGHT_FETCHING = 'RETURN_RIGHT_FETCHING';
export const RETURN_RIGHT_SUCCESS = 'RETURN_RIGHT_SUCCESS';
export const RETURN_RIGHT_FAILED = 'RETURN_RIGHT_FAILED';
export const RETURN_RIGHT_UPLOADED_SUCCESS = 'RETURN_RIGHT_UPLOADED_SUCCESS';

export const REPORT_FETCHING = 'REPORT_FETCHING';
export const REPORT_SUCCESS = 'REPORT_SUCCESS';
export const REPORT_FAILED = 'REPORT_FAILED';

export const ACTIVITYX_FETCHING = 'ACTIVITYX_FETCHING';
export const ACTIVITYX_SUCCESS = 'ACTIVITYX_SUCCESS';
export const ACTIVITYX_FAILED = 'ACTIVITYX_FAILED';
export const ACTIVITYX_REFRESH = 'ACTIVITYX_REFRESH';
export const ACTIVITYX_SEARCH = 'ACTIVITYX_SEARCH';

export const ACTIVITYY_FETCHING = 'ACTIVITYY_FETCHING';
export const ACTIVITYY_SUCCESS = 'ACTIVITYY_SUCCESS';
export const ACTIVITYY_FAILED = 'ACTIVITYY_FAILED';
export const ACTIVITYY_REFRESH = 'ACTIVITYY_REFRESH';
export const ACTIVITYY_SEARCH = 'ACTIVITYY_SEARCH';

export const ACTIVITYZ_FETCHING = 'ACTIVITYZ_FETCHING';
export const ACTIVITYZ_SUCCESS = 'ACTIVITYZ_SUCCESS';
export const ACTIVITYZ_FAILED = 'ACTIVITYZ_FAILED';
export const ACTIVITYZ_REFRESH = 'ACTIVITYZ_REFRESH';
export const ACTIVITYZ_SEARCH = 'ACTIVITYZ_SEARCH';
